### ISSUE TITLE
Location of \Foggyline\Office\Setup\EmployeeSetupFactory

### ISSUE THREAD

**Issue by stevewinni** [ajzele/B05032-Foggyline_Office#1]
Hi Sorry for the intrusion. On page 80 you reference the EmployeeSetupFactory. I can find no further reference to this file or its contents. Should it exist in the Repo?

Sorry ID10T error.... :/

Typo on one of my table create methods, resulting in referencing a table that did not exist. My Bad....

**Comment by stevewinni** [comment]
magento setup/upgrade error;

Installing data.. Upgrading data.. PHP Fatal error:  Uncaught Error: Call to a member function create() on null in /var/www/vhosts/cashmerecentre.com/dev.cashmerecentre.com/app/code/CCircle/MiniMod/Setup/UpgradeData.php:27
Stack trace:
#0 /var/www/vhosts/cashmerecentre.com/dev.cashmerecentre.com/setup/src/Magento/Setup/Model/Installer.php(826): CCircle\MiniMod\Setup\UpgradeData->upgrade(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext))
#1 /var/www/vhosts/cashmerecentre.com/dev.cashmerecentre.com/setup/src/Magento/Setup/Model/Installer.php(772): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data')
#2 /var/www/vhosts/cashmerecentre.com/dev.cashmerecentre.com/setup/src/Magento/Setup/Console/Command/UpgradeCommand.php(72): Magento\Setup\Model\Installer->installDataFixtures()
#3 /var/www/vhosts/cashmerecentre.com/dev.cashmerecentre.com/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Magento\Setup\Console\Command\UpgradeCommand->execute(Object(Symfony\Component\Co in /var/www/vhosts/cashmerecentre.com/dev.cashmerecentre.com/app/code/CCircle/MiniMod/Setup/UpgradeData.php on line 27

I thought this was created at runtime?

**Comment by gvlasov** [comment]
@stevewinni That class is automatically generated in `var/generation`, it is mentioned further in text.
